name: CI/CD Pipeline for DVWA Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and run DVWA container
      run: |
        docker-compose up -d --build
        sleep 60

    - name: Run health check
      run: curl -f http://127.0.0.1:4280 || exit 1

    - name: Shut down containers
      run: docker-compose down
